const fs = require('fs');
const path = require('path');

const collections = [
  { folder: "Women's Gallery", out: 'womensGallery.js', varName: 'womensGalleryImages' },
  { folder: "Women's Fashion", out: 'womensFashion.js', varName: 'womensFashionImages' },
  { folder: "Men's Fashion", out: 'mensFashion.js', varName: 'mensFashionImages' },
  { folder: "Children Fashion", out: 'childrenFashion.js', varName: 'childrenFashionImages' },
];

const imageExts = new Set(['.jpg', '.jpeg', '.png', '.webp']);
const videoExts = new Set(['.mp4', '.webm', '.mov']);

function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  const results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walk(full));
    } else {
      const ext = path.extname(entry.name).toLowerCase();
      const rel = path.relative(path.join(__dirname, '..', 'public'), full).replace(/\\/g, '/');
      if (imageExts.has(ext)) {
        results.push(`  { src: "/${rel}", type: "image" }`);
      } else if (videoExts.has(ext)) {
        results.push(`  { src: "/${rel}", type: "video" }`);
      }
    }
  }
  return results;
}

for (const col of collections) {
  const galleryDir = path.join(__dirname, '..', 'public', 'images', col.folder);
  const outFile = path.join(__dirname, '..', 'src', 'data', col.out);
  const images = walk(galleryDir);
  const content = `// Auto-generated by scripts/generate-gallery.js\n// Do not edit manually. Add images to public/images/${col.folder}/ and re-run.\nconst ${col.varName} = [\n${images.join(',\n')},\n];\n\nexport default ${col.varName};\n`;
  fs.writeFileSync(outFile, content, 'utf8');
  console.log(`Generated ${col.out} with ${images.length} images`);
}
